const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('rpcCluster', {
  scanWorkers: () => ipcRenderer.invoke('scan-workers'),
  probeCloudWorker: (ip, port) => ipcRenderer.invoke('probe-cloud-worker', { ip, port }),
  scanCloudWorkers: (targets) => ipcRenderer.invoke('scan-cloud-workers', targets),
  listModels: () => ipcRenderer.invoke('list-models'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  loadConfig: () => ipcRenderer.invoke('load-config'),
  openConfigFolder: () => ipcRenderer.invoke('open-config-folder'),
  testCluster: (config) => ipcRenderer.invoke('test-cluster', config),
  detectHostHardware: () => ipcRenderer.invoke('detect-host-hardware'),
  getLlamaDownloadUrl: (variant) => ipcRenderer.invoke('get-llama-download-url', variant),
  installLlamaServer: (url) => ipcRenderer.invoke('install-llama-server', url),
  onInstallProgress: (cb) => ipcRenderer.on('install-progress', (event, data) => cb(data)),
  restartApp: () => ipcRenderer.invoke('restart-app'),
  openExternalUrl: (url) => ipcRenderer.invoke('open-external-url', url),
  checkLlamaInstallation: () => ipcRenderer.invoke('check-llama-installation'),
  getModels: () => ipcRenderer.invoke('get-models'),
  addModel: (model) => ipcRenderer.invoke('add-model', model),
  updateModel: (id, changes) => ipcRenderer.invoke('update-model', { id, changes }),
  removeModel: (id) => ipcRenderer.invoke('remove-model', id),
  startModel: (id) => ipcRenderer.invoke('start-model', id),
  stopModel: (id) => ipcRenderer.invoke('stop-model', id),
  stopAllModels: () => ipcRenderer.invoke('stop-all-models'),
  getModelStatus: (id) => ipcRenderer.invoke('get-model-status', id),
});
